version: '3.3'

services:
  nodejs:
    image: node:alpine
    volumes:
      - ./server:/app
    restart: always
    working_dir: /app
    command: sh -c "npm install && npm start"
    ports:
      - "3000:3000"
    networks:
      - appnet

  web:
    image: node:alpine
    volumes:
      - ./client:/app
    restart: always
    working_dir: /app
    command: sh -c "npm install && npm start"
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=dev
    networks:
      - appnet

  redis:
    image: "redis:alpine"
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - appnet

networks:
  appnet:
    driver: "bridge"
